"use client";
// import Head from "next/head";
import { useRouter } from "next/navigation";
import NewTripForm from "../../component/meetups/NewTripForm";
// import { Fragment } from "react";
// export const metadata: Metadata = {
//   title: "Planner",
//   description: "Generated by create next app",
// };
function NewMeetupPage() {
  const router = useRouter();
  async function addMeetupHandler(enteredData) {
    // console.log(enteredData);
    const response = await fetch("api/newtrip", {
      method: "POST",
      body: JSON.stringify(enteredData),
    });
    // const data = await response.json();
    console.log(response.statusText);
    router.push("/");
  }
  return (
    <NewTripForm onAddMeetup={addMeetupHandler} />
    // <Fragment>
    //   <Head>
    //     <title>Add Your Own Trip</title>
    //   </Head>
    // </Fragment>
  );
}
export default NewMeetupPage;
